<template>
  <svg
    class="hz-icon"
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
  >
    <rect
      width="23"
      height="23"
      x=".5"
      y=".5"
      fill="#FFF"
      fill-rule="evenodd"
      stroke="#CED4DA"
      rx="11.5"
    />
  </svg>
</template>
